# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: niklasnilsson
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: nightowls-bonzai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: nightowls-bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::376129862797:role/LambdaDynamoDBuserRole

functions:
  GetRooms:
    handler: functions/GetRooms/index.handler
    events:
      - httpApi:
          path: /api/rooms
          method: get
  PostRooms:
      handler: functions/PostRooms/index.handler
      events:
        - httpApi:
            path: /api/rooms
            method: post




resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'bonzai-db'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'  
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST